# Generated by Django 2.0.6 on 2018-06-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bio', models.TextField(max_length=200)),
                ('picture', models.ImageField(upload_to='')),
                ('junior', models.BooleanField()),
            ],
        ),
    ]
