# Generated by Django 2.0.6 on 2018-06-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(max_length=1000)),
                ('picture', models.ImageField(upload_to='about_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='driver',
            name='picture',
            field=models.ImageField(upload_to='driver_images/'),
        ),
    ]
