# Generated by Django 2.0.6 on 2018-06-10 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180609_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
